version: '3.8'

services:
  deefind:
    image: ghcr.io/2t0m/deefind:latest
    container_name: deefind
    ports:
      - "1234:1234"
    environment:
      - DOWNLOADER_API_URL=http://ip-address
      - NAVIDROME_URL=http://ip-address:4533
      - NAVIDROME_USER=admin
      - NAVIDROME_PASS=admin
    restart: unless-stopped
