version: '3.8'

services:
  deefind:
    image: ghcr.io/2t0m/deefind:main
    container_name: deefind
    ports:
      - "1234:1234"
    environment:
      - DOWNLOADER_API_URL="${DOWNLOADER_API_URL}"
      - NAVIDROME_URL="${NAVIDROME_URL}"
      - NAVIDROME_USER="${NAVIDROME_USER}"
      - NAVIDROME_PASS="${NAVIDROME_PASS}"
    restart: unless-stopped
